### ISSUE TITLE
add roGridScreen

### ISSUE THREAD

**Issue by xoceunder** [cbojar/jb-roku#10]
@allanjude 
@cbojar 

add roGridScreen

**Comment by cbojar** [comment]
Why, where, and how? The requested feature is so specific (and the context so unspecified) that I feel there needs to be more explanation for why it is needed.

**Comment by xoceunder** [comment]
I replied that if the category has no sub category displays the content this way
@cbojar 
![twhfijl](https://cloud.githubusercontent.com/assets/12431116/9610242/43466ede-50a6-11e5-8fb8-cea0f858c4c9.png)
