### ISSUE TITLE
Unceremoniously crashes if there are no upcoming events

### ISSUE THREAD

**Issue by cbojar** [cbojar/jb-roku#5]
The live stream screen pulls an event feed. If that feed has no events (say if we're only looking a week ahead but @ChrisLAS takes a week off), then the app unceremoniously crashes out to the home screen. Basic fix is to always make sure there are always events in the feed. I need to add a check in the app code to count how many events there are, and handle appropriately if there aren't any.

**Comment by ChrisLAS** [comment]
Now if thats not a statement of hardcore JB is.. IDK what is. Thanks man :) Probably won't need to worry about it for quite a while tho!

**Comment by cbojar** [comment]
@ChrisLAS Actually...we did run into this bug, for about 20 minutes. It worked fine before because it was able to pull in a week's worth of show data. Then **you** went and took a week off. :smirk: Now I check for the next `n` events, and it will keep working even if something else unexpected comes up. :+1:
