### ISSUE TITLE
this code implement

### ISSUE THREAD

**Issue by xoceunder** [cbojar/jb-roku#7]
@cbojar  @allanjude  I am seeking some kind of work to create a platform

**Comment by cbojar** [comment]
I'm not sure what you ae asking. Could you please elaborate?

**Comment by xoceunder** [comment]
forgive is that used a google translator is that I aver if you can change and some things implementarle my application that I have check

**Comment by cbojar** [comment]
I'm sorry, but I still don't understand what you are asking.

**Comment by xoceunder** [comment]
@cbojar Any email to communicate with you
